# Generated by Django 4.1 on 2023-04-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male'), ('other', 'other')], max_length=6),
        ),
    ]
